language: android
android:
        components:
                - platform-tools
                - build-tools-27.0.3
                - android-27
script:
        - cd injector && ./gradlew build install
        - cd ../injector-android-example && ./gradlew build
        - cd ../
after_success:
        - ./cd/before-deploy.sh
        - ./cd/deploy.sh
