language: android
android:
        components:
                - platform-tools
                - build-tools-27.0.3
                - android-27
script:
        - cd cd/
        - ./before-deploy.sh
        - cd ../
        - cd injector && ./gradlew build install
        - cd ../injector-android-example && ./gradlew build
after_success:
        - cd ../cd/
        - ./deploy.sh
