language: android
android:
        components:
                - platform-tools
                - build-tools-28.0.3
                - android-29
script:
        - cd .buildscript/
        - ./before.sh
        - cd ../injector && ./gradlew build install
        - cd ../injector-android-example && ./gradlew build
after_success:
        - cd ../.buildscript/
        - ./deploy.sh

cache:
        directories:
                - $HOME/.gradle
